server:
  port: 8090
  
spring:
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reinforce_db?useSSL=false
    username: root
    password: Hda77063!!@
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        
logging:
 level:
   org.springframework.aop: ERROR
   com.reinforce: INFO  
 pattern:
   console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
   file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"  
 file:
   max-size:
     10MB
   name:
     myLogs.log  
     
management:
 endpoints:
   web:
     exposure:
       include: "*"